apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-dzll
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-dzll
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-dzllrdhs
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dc-metro-map-dzll
    weight: 100
status: {}
